scara_cpe:

# Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


# Position Controllers ---------------------------------------

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_1_joint
    pid: {p: 10.0, i: 0.0, d: 0.1}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_2_joint
    pid: {p: 10.0, i: 0.0, d: 0.1}


# Trajectory Controllers --------------------------------------

  scara_cpe_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - shoulder_1_joint
      - shoulder_2_joint


    gains: # Required because we're controlling an effort interface
      shoulder_1_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 0}
      shoulder_2_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 0}
